# Generated by Django 2.1.2 on 2018-10-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=16, verbose_name='lecture id')),
                ('division', models.CharField(default=1, max_length=8, verbose_name='division')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('type', models.IntegerField(blank=True, choices=[(0, '중핵필수'), (4, '중핵필수선택'), (2, '자유선택교양'), (3, '전공필수'), (4, '전공선택'), (5, '전공기초교양')], default=0, null=True, verbose_name='lecture type')),
                ('field', models.IntegerField(blank=True, choices=[(0, '학문기초'), (1, '인성과창의력'), (2, '사상과역사'), (3, '사회와문화'), (4, '융합과창업'), (5, '자연과과학기술'), (6, '세계와지구촌'), (7, '생명과 과학'), (8, '인성과도덕'), (9, '역사와문화'), (10, '사회와제도'), (11, '예술과생활'), (12, '지구촌의이해'), (13, '역량강화')], default=0, null=True, verbose_name='lecture field')),
                ('grade', models.IntegerField(blank=True, default=1, null=True, verbose_name='grade')),
                ('point', models.FloatField(blank=True, default=1.0, null=True, verbose_name='point')),
                ('language', models.IntegerField(blank=True, choices=[(0, '한국어'), (1, '영어'), (2, '영어/한국어')], default=0, null=True, verbose_name='language')),
                ('classroom', models.CharField(blank=True, max_length=16, null=True, verbose_name='classroom')),
                ('professor', models.CharField(blank=True, max_length=32, null=True, verbose_name='professor')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lecture.Department', verbose_name='department')),
                ('origin_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_lectures', to='lecture.Department', verbose_name='origin department')),
            ],
        ),
        migrations.CreateModel(
            name='LectureTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금')], default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
            ],
        ),
    ]
