# Generated by Django 2.1.3 on 2018-11-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='category',
        ),
        migrations.AddField(
            model_name='lecture',
            name='category',
            field=models.ManyToManyField(related_name='lectures', to='lecture.Category', verbose_name='category'),
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='lecture',
            name='subcategory',
            field=models.ManyToManyField(related_name='lectures', to='lecture.Subcategory', verbose_name='subcategory'),
        ),
    ]
