# Generated by Django 2.1.2 on 2018-10-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='grade',
            field=models.IntegerField(default=1, null=True, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='point',
            field=models.FloatField(default=1.0, null=True, verbose_name='point'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.IntegerField(choices=[(0, '중핵필수'), (1, '중핵필수선택'), (2, '자유선택교양'), (3, '전공필수'), (4, '전공선택'), (5, '전공기초교양')], default=0, null=True, verbose_name='lecture type'),
        ),
    ]
