# Generated by Django 2.1.2 on 2018-10-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20181020_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='classroom',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='classroom'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='field',
            field=models.IntegerField(blank=True, choices=[(0, '학문기초'), (1, '인성과창의력'), (2, '사상과역사'), (3, '사회와문화'), (4, '융합과창업'), (5, '자연과과학기술'), (6, '세계와지구촌'), (7, '생명과 과학'), (8, '인성과도덕'), (9, '역사와문화'), (10, '사회와제도'), (11, '예술과생활'), (12, '지구촌의이해'), (13, '역량강화')], default=0, null=True, verbose_name='lecture field'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='grade',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='language',
            field=models.IntegerField(blank=True, choices=[(0, '한국어'), (1, '영어'), (2, '영어/한국어')], default=0, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='point',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='point'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='professor'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, '중핵필수'), (1, '중핵필수선택'), (2, '자유선택교양'), (3, '전공필수'), (4, '전공선택'), (5, '전공기초교양')], default=0, null=True, verbose_name='lecture type'),
        ),
    ]
