# Generated by Django 2.1.2 on 2018-11-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20181024_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='field',
        ),
        migrations.AddField(
            model_name='lecture',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, '없음'), (1, '경제'), (2, '경영'), (3, '언어'), (4, '방송'), (5, '인문'), (6, '심리'), (7, '역사'), (8, '스포츠'), (9, '진로'), (10, '문화'), (11, '사회'), (12, '과학'), (13, '수학'), (14, '예술'), (15, '종교'), (16, '생활'), (17, '취미'), (18, '컴퓨터'), (19, '기술'), (20, '융합'), (21, '만화')], default=0, null=True, verbose_name='lecture category'),
        ),
    ]
