# Generated by Django 2.1.3 on 2018-11-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20181113_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturetime',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='lecture.Lecture'),
        ),
    ]
