# Generated by Django 2.1.3 on 2018-12-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20181120_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='place',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='place id'),
        ),
    ]
