# Generated by Django 2.1.2 on 2018-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20181022_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='field',
            field=models.IntegerField(blank=True, choices=[('학문기초', 0), ('인성과창의력', 1), ('사상과역사', 2), ('사회와문화', 3), ('융합과창업', 4), ('자연과과학기술', 5), ('세계와지구촌', 6), ('생명과 과학', 7), ('인성과도덕', 8), ('역사와문화', 9), ('사회와제도', 10), ('예술과생활', 11), ('지구촌의이해', 12), ('역량강화', 13)], default=0, null=True, verbose_name='lecture field'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='language',
            field=models.IntegerField(blank=True, choices=[('한국어', 0), ('영어', 1), ('영어/한국어', 2)], default=0, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.IntegerField(blank=True, choices=[('중핵필수', 0), ('중핵필수선택', 4), ('자유선택교양', 2), ('전공필수', 3), ('전공선택', 4), ('전공기초교양', 5)], default=0, null=True, verbose_name='lecture type'),
        ),
    ]
