# Generated by Django 2.1.3 on 2018-11-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20181119_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturetime',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='lecturetime',
            old_name='start_time',
            new_name='start',
        ),
    ]
