# Generated by Django 2.1.3 on 2018-11-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20181119_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='uuid',
            new_name='code',
        ),
    ]
