# Generated by Django 2.1.3 on 2018-12-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_lecture_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturetime',
            name='place',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
