# Generated by Django 2.1.3 on 2018-11-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_auto_20181119_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='subcategory',
            field=models.IntegerField(blank=True, choices=[(0, '없음')], default=0, null=True, verbose_name='lecture subcategory'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, '없음')], default=0, null=True, verbose_name='lecture category'),
        ),
    ]
