# Generated by Django 2.1.4 on 2018-12-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_lecturetime_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturetime',
            name='place',
            field=models.IntegerField(blank=True, db_index=True, default=-1, null=True),
        ),
    ]
