# Generated by Django 2.1.4 on 2018-12-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_auto_20181205_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='place',
        ),
    ]
