# Generated by Django 2.1.2 on 2018-10-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_department_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
    ]
